import type { RootCauseAnalysis, RemediationResult, IncidentType } from '../types.js';

export interface PRGenerationRequest {
  incidentId: string;
  incidentType: IncidentType;
  rootCause: RootCauseAnalysis;
  affectedResources: string[];
  suggestedFix?: string;
}

export interface GeneratedPR {
  branchName: string;
  title: string;
  body: string;
  files: Array<{ path: string; content: string; action: 'create' | 'modify' }>;
  labels: string[];
  reviewers: string[];
}

/**
 * PR Generator for code-level remediation (pattern from Resolve.ai).
 * Generates structured PR descriptions with root cause context.
 * Actual Git operations require external integration (GitHub API).
 */
export class PRGenerator {
  /**
   * Generate a PR structure for a code-level fix.
   * Does NOT create the actual PR — returns the structure for external tooling.
   */
  generate(request: PRGenerationRequest): GeneratedPR {
    const branchName = `fix/incident-${request.incidentId}-${request.incidentType}`;
    const title = `[Auto-Remediation] Fix ${request.incidentType.replace(/_/g, ' ')} in ${request.affectedResources.join(', ')}`;

    const body = [
      '## Root Cause Analysis',
      `**Type:** ${request.incidentType}`,
      `**Confidence:** ${(request.rootCause.confidence * 100).toFixed(0)}%`,
      `**Root Cause:** ${request.rootCause.rootCause}`,
      '',
      '### Causal Chain',
      ...request.rootCause.causalChain.map((link, i) =>
        `${i + 1}. **${link.entity}** (${link.entityType}): ${link.issue} [${(link.confidence * 100).toFixed(0)}% confidence]`
      ),
      '',
      '### Evidence Sources',
      ...request.rootCause.evidenceSources.map(s => `- ${s}`),
      '',
      '## Suggested Fix',
      request.suggestedFix ?? '_Requires manual review — no automated fix available._',
      '',
      '## Impact',
      `Affected resources: ${request.affectedResources.join(', ')}`,
      '',
      '---',
      '_Generated by Data Workers Incident Agent. Review before merging._',
    ].join('\n');

    return {
      branchName,
      title,
      body,
      files: [], // Actual file changes require LLM code generation
      labels: ['auto-remediation', `incident-${request.incidentType}`],
      reviewers: [], // Configured via settings
    };
  }

  /**
   * Generate fix suggestions based on incident type.
   */
  suggestFix(incidentType: IncidentType, rootCause: string): string {
    const suggestions: Record<IncidentType, string> = {
      schema_change: `Review and update downstream dbt models to accommodate schema change: ${rootCause}`,
      source_delay: `Add retry logic or circuit breaker for delayed source. Consider backup source configuration.`,
      resource_exhaustion: `Optimize query/compute or increase resource allocation. Review recent workload changes.`,
      code_regression: `Rollback recent deployment or apply hotfix. Check CI/CD pipeline for test gaps.`,
      infrastructure: `Verify infrastructure health. Check service endpoints and network connectivity.`,
      quality_degradation: `Add data quality checks for affected columns. Review upstream pipeline changes.`,
    };
    return suggestions[incidentType] ?? 'Requires manual investigation.';
  }
}
